name: CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    docker-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Build Docker Image
              run: docker build -t ${{vars.DOCKERHUB_USERNAME}}/${{vars.DOCKERHUB_REPOSITORY}}:${{github.run_number}} .
            - name: Run Docker Container
              run: docker run -d -p 80:3000 ${{vars.DOCKERHUB_USERNAME}}/${{vars.DOCKERHUB_REPOSITORY}}:${{github.run_number}}
            - name: Run Tests via Liatrio's apprentice-action
              uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with: 
                username: ${{vars.DOCKERHUB_USERNAME}} 
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Push Docker Image
              run: docker push ${{vars.DOCKERHUB_USERNAME}}/${{vars.DOCKERHUB_REPOSITORY}}:${{github.run_number}}


